server.port: 8081

security:
  ignored: /docs/**
  oauth2.resource:
    user-info-uri: http://uaa/me
    load-balanced: true

management:
  context-path: /manage

logging:
  level:
    com.netflix.discovery: 'OFF'

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: 'jdbc:mysql://localhost:3306/booking'
    username: root
    tomcat:
      max-wait: 10000
      max-idle: 100
      max-active: 100
      test-on-borrow: true
      validation-query: SELECT 1
      test-while-idle: true
      remove-abandoned: true
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: validate
