server.port: 8443

spring:
  application:
    name: booking
  h2.console:
    enabled: true
    path: /console
<<<<<<< HEAD
  jpa.hibernate.ddl-auto: validate
=======
>>>>>>> 76ef394c3d56a621ccb53971dc61f6a40100b41d

security.ignored: /console/**

logging:
  level:
    com.netflix.discovery: 'OFF'