server.port: 8081

security:
  ignored: /console/**,/docs/**
  oauth2.resource:
    user-info-uri: http://uaa/me
    load-balanced: true

logging:
  level:
    com.netflix.discovery: 'OFF'

spring:
  application:
    name: bookings
  h2.console:
    enabled: true
    path: /console
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
      validation-query: SELECT 1
      test-while-idle: true
      remove-abandoned: true
  jpa:
    database: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
