server.port: 8081

spring:
  application:
    name: booking
  h2.console:
    enabled: true
    path: /console
  jpa.hibernate.ddl-auto: validate

security:
  ignored: /console/**
  oauth2.resource:
    user-info-uri: http://uaa/me
    load-balanced: true

logging:
  level:
    com.netflix.discovery: 'OFF'