spring:
  application:
    name: gateway

logging:
  level:
    com.netflix.discovery: 'OFF'

security:
  ignored: /uaa/**
  oauth2.resource:
    prefer-token-info: false
    user-info-uri: http://uaa/me
    load-balanced: true

zuul:
  sensitive-headers: