server.port: 9090

security:
  basic.enabled: false
  ignored: /**

spring:
  social.twitter:
    appId: 7c7ANtB6g51L8nXicy8tfVYaH
    appSecret: FRkm8zYoKqEczLS99EL6Y6h3hKsoIwMqNXmqIYosBwnKvIUeRC

booking:
  endpoints:
    customers: http://localhost:8082
    airports: http://localhost:8083/airports