server.port: 9090

security:
  basic.enabled: false
  ignored: /**

spring:
  social.twitter:
    appId: $key
    appSecret: $secret

booking:
  endpoints:
    customers: http://localhost:8082
    airports: http://localhost:8083/airports